name: "pysparkdbt_project_internal"
version: 1.0.0
config-version: 2

profile: "default"

# File paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Target directory
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  pysparkdbt_project_internal:
    gold:
      +materialized: table
    silver:
      +materialized: table
      +schema: silver
